language: php

dist: xenial

php:
    - 7.2

services:
    - mysql

before_install:
    - cp config/config.php.example config/config.php
    - cp config/phinx.php.example config/phinx.php
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade -u root -ppassword
    - sudo service mysql restart
    - mysql -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS startplats_test;'

script:
    - composer install
    - ./bin/phinx.sh migrate -e test
    - composer test
    - ./bin/psr-2.sh -v --diff --dry-run --stop-on-violation